[package]
name = "grain-128"
version = "0.1.0"
edition = "2024"

[dependencies]
aead = { version = "0.6.0-rc.3", default-features = false }
cipher = { version = "0.5.0-rc.2", features = ["stream-wrapper"] }
num = "0.4"

[dependicies.num]
version = "0.4"
default-features = false


[dev-dependencies]
#cipher = { version = "0.5.0-rc.1", features = ["dev"] }
hex-literal = "1"
proptest = "1.9.0"
rand = "0.9.2"


[features]
zeroize = ["cipher/zeroize"]

[profile.release]
debug = true
codegen-unti = 1
lto = "thin"
